# Base Image
FROM node:14.13.0 AS build

WORKDIR /usr/src/app
COPY ./package*.json ./
RUN CI=true npm install

# Technically moving package*.json files twice, but fine so we don't prematurely invalidate npm install
COPY . ./
RUN REACT_APP_IS_DOCKER=true npm run build

# Web Server
FROM nginx:stable-alpine
COPY --from=build ./usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]