
# Base Image
FROM node:latest

ENV NODE_ENV=development
ENV PORT=4242
ENV CHOKIDAR_USEPOLLING=true

WORKDIR /usr/src/app
COPY ./client/package*.json /usr/src/app/
RUN cd /usr/src/app && CI=true npm install

EXPOSE 4242
CMD ["npm", "run", "start"]

# build the image with this command
# docker build --tag docker_demo:latest --file Dockerfile.dev .