
# Base Image
FROM node:latest

ENV NODE_ENV=development
ENV PORT=3000
ENV CHOKIDAR_USEPOLLING=true

WORKDIR /usr/src/app
COPY ./server/package*.json /usr/src/app/
RUN cd /usr/src/app && CI=true npm install

EXPOSE 3000
CMD ["npm", "run", "serve"]

# build the image with this command
# docker build --tag docker_demo:latest --file Dockerfile.dev .