version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Installing frontend
          command: |
            cd client
            npm ci
      - run:
          name: Creating frontend build
          command: |
            cd client
            npm run build
      - run:
          name: Installing server
          command: |
            cd server
            npm ci
      - run:
          name: Creating server build
          command: |
            cd server
            npm run build
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          paths:
            - client/build
            - server/lib
            - server/node_modules
            - server/package.json
            - server/package-lock.json
  test-client:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Installing
          command: |
            cd client
            npm ci
      - run:
          name: Running Test suite
          command: |
            cd client
            npm run test
  test-server:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Installing
          command: |
            cd server
            npm ci
      - run:
          name: Running Test suite
          command: |
            cd server
            npm run test
  deploy:
    machine:
      image: default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "35:34:58:07:07:41:58:98:12:72:1c:da:47:23:80:e3"
      - attach_workspace:
          at: .
      - run:
          name: Deploy Frontend
          command: |
            ls -la
            rsync -r ./client/build/ $SSH_USER@$SSH_HOST:/var/www/gosyp.io/public_html
      - run:
          name: Deploy CMS
          command: |
            rsync -r ./server/ $SSH_USER@$SSH_HOST:~/gosyp/server

workflows:
  build-test-and-deploy:
      jobs:
        - build
        - test-client:
            requires:
              - build
        - test-server:
            requires:
              - build
        - deploy:
            requires:
              - test-server
              - test-client
            filters:
              branches:
                only:
                  - production