apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: node
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: node
        track: stable
    spec:
      containers:
        - name: backend
          image: mlcochrane/test-back:test
          ports:
            - name: http
              containerPort: 3001
          env:
            - name: "MONGODB_URI"
              value: "mongodb://superuser:secretpassword@mongodb.default.svc.cluster.local:27017/gosyp_db"
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: node
    track: stable
  ports:
  - port: 3001
    targetPort: 3001