apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: node
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: node
        track: stable
    spec:
      containers:
        - name: backend
          image: mlcochrane/test-back:test
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-entrypoint
  namespace: default
spec:
  selector:
    app: node
    track: stable
  ports:
  - port: 3000
    targetPort: 3000