apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: react
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: react
        track: stable
    spec:
      containers:
        - name: frontend
          image: mlcochrane/test-rec:test
          ports:
            - name: http
              containerPort: 80
---
# This would ideally be a LoadBalancer instead
apiVersion: v1
kind: Service
metadata:
  name: frontend-entrypoint
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: react
    track: stable
  ports:
  - port: 80
    targetPort: 80