export const RECEIVE_ROOM_ID = 'RECEIVE_ROOM_ID';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const SET_NEEDS_RESIZE = 'SET_NEEDS_RESIZE';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';