export const FETCH_NAVIGATION_STARTED = 'FETCH_NAVIGATION_STARTED'
export const RECIEVE_NAVIGATION = 'RECIEVE_NAVIGATION'
export const RECIEVE_NAVIGATION_ERROR = 'RECIEVE_NAVIGATION_ERROR'

export const FETCH_PROJECTS_STARTED = 'FETCH_PROJECTS_STARTED'
export const RECIEVE_ALL_PROJECTS = 'RECIEVE_ALL_PROJECTS'
export const RECIEVE_SINGLE_PROJECT = 'RECIEVE_SINGLE_PROJECT'
export const RECIEVE_PROJECTS_ERROR = 'RECIEVE_PROJECTS_ERROR'

export const FETCH_HOMEPAGE_STARTED = 'FETCH_HOMEPAGE_STARTED'
export const RECIEVE_HOMEPAGE = 'RECIEVE_HOMEPAGE'
export const RECIEVE_HOMEPAGE_ERROR = 'RECIEVE_HOMEPAGE_ERROR'

export const FETCH_ABOUT_STARTED = 'FETCH_ABOUT_STARTED'
export const RECIEVE_ABOUT = 'RECIEVE_ABOUT'
export const RECIEVE_ABOUT_ERROR = 'RECIEVE_ABOUT_ERROR'

export const FETCH_BLOG_STARTED = 'FETCH_BLOG_STARTED'
export const RECIEVE_POSTS = 'RECIEVE_POSTS'
export const RECIEVE_SINGLE_POST = 'RECIEVE_SINGLE_POST'
export const RECIEVE_BLOG_ERROR = 'RECIEVE_BLOG_ERROR'
export const RECIEVE_FEATURED_POSTS = 'RECIEVE_FEATURED_POSTS'

export const FETCH_CONTACT_STARTED = 'FETCH_CONTACT_STARTED'
export const RECIEVE_CONTACT = 'RECIEVE_CONTACT'
export const RECIEVE_CONTACT_ERROR = 'RECIEVE_CONTACT_ERROR'

export const UPDATE_HISTORY = 'UPDATE_HISTORY'

export const FETCH_EXPERTISE_STARTED = 'FETCH_EXPERTISE_STARTED'
export const RECIEVE_EXPERTISE = 'RECIEVE_EXPERTISE'
export const RECIEVE_EXPERTISE_ERROR = 'RECIEVE_EXPERTISE_ERROR'