# Base Image
FROM node:latest

WORKDIR /usr/src/app
COPY ./package*.json ./tsconfig.json ./.babelrc ./
RUN CI=true npm install

COPY . ./

RUN npm run build

ARG FRONTEND_URL
ENV FRONTEND_URL="${FRONTEND_URL}"
ENV NODE_ENV=production
ENV PORT=3000
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000
CMD ["npm", "run", "serve"]
