# Base Image
FROM mlcochrane/gosyp-ci:alpha-1

USER circleci

ENV NPM_CONFIG_PREFIX=/home/circleci/.npm-global
ENV PATH=$PATH:/home/circleci/.npm-global/bin

WORKDIR /home/circleci/project
COPY package*.json wait-it-out.sh jest.config.js ./
RUN CI=true npm install
COPY setup ./setup
COPY __tests__ ./__tests__

CMD ["bash", "./wait-it-out.sh", "-t", "web:80", "-c", "npm run test"]
